services:
  db:
    container_name: 'db_mysql'
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ../db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 50s
      retries: 10
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - ENV=${ENV}
    volumes:
      - /tmp/app/mysqld:/run/mysqld
      - .:/app
      - /Volumes/homes/Alex/ebook/test:/volumes/homes/Alex/ebook/test
    depends_on:
      db:
        condition: service_healthy
        restart: true
