services:
  db:
    container_name: 'db_mysql'
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
    volumes:
      - /volume1/docker/booker/app/mysqld:/var/run/mysqld
      - /volume1/docker/booker/db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 50s
      retries: 10
  web:
    image: sonpero/booker-web:1.1.0
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - /volume1/docker/booker/app/mysqld:/run/mysqld
      - /volume1/homes/web_library:/volumes/homes/web_library
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"