services:
  nginx:
    image: sonpero/booker-nginx:1.1.1
    restart: always
    volumes:
      - /volume1/homes/web_library:/app/static
    ports:
      - "800:800"
    networks:
      - django-network
networks:
  django-network:
    external: true