# Generated by Django 4.1.7 on 2023-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='books')),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
